name: Sumit Suman
description: Product and Business in San Francisco 
meta_description: "Blogging about building messaging, chat, and collaboration products"

aboutPage: true

markdown: kramdown
#redcarpet:
   # extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

highlighter: rouge

# Permalinks
permalink:        pretty
#permalink:       /:year/:title/



paginate: 20
baseurl: /
domain_name: 'http://sumitsuman.com'
google_analytics: 'UA-52590209-1'
disqus: false
disqus_shortname: 'arraysum'

# Details for the RSS feed generator
url:            'http://sumitsuman.com'
author:         'Sumit Suman'
authorTwitter:  'arraysum'

gems:
  #- jekyll-redirect-from
  - jekyll-paginate

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post


