# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sumit Suman
tagline:          
url:              http://sumitsuman.com
shorturl:         sumitsuman.com

paginate:         1
baseurl:          /

author:
  name:           Sumit Suman
  url:            https://twitter.com/arraysum

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/sumitsuman/sumitsuman.github.io

# Customization - Top navigation
pages_list:
  #About: '/about'
  Blog: '/blog'
  Portfolio: '/portfolio'
  #Contact: '/contact'


  # Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from