# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sumit Suman
tagline:
url:              http://sumitsuman.com
paginate:         1
baseurl:          /
author:
  name:           Sumit Suman
  url:            https://twitter.com/arraysum
  email:          sumitsuman+website@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/sumitsuman/sumitsuman.github.io

# Customization - Top navigation
pages_list:
  About: '/about'
  Portfolio: '/portfolio'
  #Archive: '/archive'
  #Contact: '/contact'